name: Lint and Test

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java-version: [8,11,17,18,19,20,21,22,23]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: oracle
          cache: maven
      - name: Check current Java version
        run: java -version

        # Step 3: Validate Maven dependencies
      - name: Validate Maven dependencies with Java ${{ matrix.java-version }}
        working-directory: ./paytrailpayment-sdk
        run: mvn dependency:resolve
  
        # Step 4: Run Maven lint checks (Checkstyle, SpotBugs, etc.)
      - name: Run Maven lint checks with Java ${{ matrix.java-version }}
        working-directory: ./paytrailpayment-sdk
        run: mvn checkstyle:check

        # Step 5: Run Maven tests
      - name: Run Maven tests with Java ${{ matrix.java-version }}
        working-directory: ./paytrailpayment-sdk
        run: mvn test